#!/bin/bash
file iamafile#!/bin/bash
file iamafile#!/bin/bash
file iamafile#!/bin/bash
file iamafile#!/bin/bash
file iamafile#!/bin/bash
file iamafile#!/bin/bash
file iamafile#!/bin/bash
file iamafile#!/bin/bash
file iamafile
